### ISSUE TITLE
Status 'failed' returned when sending certain data

### ISSUE THREAD

**Issue by mtornow** [julwil/ccs4dt#41]
In approx. 5-10% of the API calls, the status of the input batch is 'failed' (in the returned JSON) with HTTP status code 200. There is no regularity that I can see in the requests, see one example in the files attached (location & synthetic measurement data)
[location_payload_API-status_failed.txt](https://github.com/julwil/ccs4dt/files/7699881/location_payload_API-status_failed.txt)
[synthetic_measurement_payload_API-status_failed.txt](https://github.com/julwil/ccs4dt/files/7699883/synthetic_measurement_payload_API-status_failed.txt)
.

**Comment by mtornow** [comment]
This issue also persists, if the requests are made via postman using the same data.

**Comment by mtornow** [comment]
Additional failed example:
[location_payload _API-status_failed_example2.txt](https://github.com/julwil/ccs4dt/files/7699892/location_payload._API-status_failed_example2.txt)
[synthetic_measurement_payload _API-status_failed_example2.txt](https://github.com/julwil/ccs4dt/files/7699893/synthetic_measurement_payload._API-status_failed_example2.txt)

**Comment by mtornow** [comment]
(Files are JSON files, but github only accepts .txt uploads)

**Comment by julwil** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug: Processing fails](https://trello.com/c/DQP7IGfa/67-bug-processing-fails)

**Comment by julwil** [comment]
@mtornow Maybe we can look at it together this afternoon. I didn't manage to reproduce.
